<?php
function groceries_menu() {
    $items = array();
    $items['groceries'] = array (
        'title' => 'Groceries',
        'page callback' => 'groceries',
        'access callback' => TRUE,
        'type' => MENU_NORMAL_ITEM,
    );
    return $items;
}

function groceries() {
    $list['eggs'] = array(
        'quantity' => 2,
        'price' => 2,
    );
    $list['milk'] = array(
        'quantity' => 3,
        'price' => 2,
    );
    $list['bacon'] = array(
        'quantity' => 50,
        'price' => 3,
    );


    $result = null;
    $test = "";

    foreach ($list as $key => $list_item) {

        $test = $test . $list_item['quantity'] . " " . $key ." at"  . " $" . $list_item['price'] . " each";

        $item_price = $list_item['quantity'] * $list_item['price'];

        $test = $test . "<li>$" . $item_price . "</li></p>";
        // $result = $result . "</p>";

        $result = $result + $item_price;

    }

    return  '<p>Brian and Reids SUPER AWESOME list two: </p><p>' . $test . ' </p>' . 'TOTAL PRICE: $' . $result;

}
