<?php
function groceries_menu() {
    $items = array();
    $items['groceries'] = array (
        'title' => 'Groceries',
        'page callback' => 'groceries',
        'access callback' => TRUE,
        'type' => MENU_NORMAL_ITEM,
    );
    return $items;
}

function groceries() {
    $list['eggs'] = array(
        'item' => 'eggs',
        'quantity' => 2,
        'price' => 1.99,
    );
    $list['milk'] = array(
        'item' => 'milk',
        'quantity' => 3,
        'price' => 1.50,
    );
    $list['bacon'] = array(
        'item' => 'bacon',
        'quantity' => 50,
        'price' => 3,
    );


    // return '<p> This </p>';
    $result = "";

    foreach ($list as $list_item) {
        $result = $result . "<p>";
        foreach ($list_item as $item_value) {
            $result = $result . " " . $item_value . " ";

        }

        $result = $result . "</p>";
        // $total_price = ['quantity'] * ['price'];
        // echo "<p> $total_price </p>";
    }

    return  '<p>This list: ' . $result . ' </p>';

}
